TEAM_CODE_MAPPINGS = {
    "GB": "GBP",
    "KC": "KCC",
    "LA": "LAR",
    "NE": "NEP",
    "NO": "NOS",
    "SD": "SDC",
    "SF": "SFO",
    "TB": "TBB",
    "WSH": "WAS",
    "JAX": "JAC",
}

TEAM_NAME_MAPPINGS = {
    "ARI": "Arizona Cardinals",
    "ATL": "Atlanta Falcons",
    "BAL": "Baltimore Ravens",
    "BUF": "Buffalo Bills",
    "CAR": "Carolina Panthers",
    "CHI": "Chicago Bears",
    "CIN": "Cincinnati Bengals",
    "CLE": "Cleveland Browns",
    "DAL": "Dallas Cowboys",
    "DEN": "Denver Broncos",
    "DET": "Detroit Lions",
    "GBP": "Green Bay Packers",
    "HOU": "Houston Texans",
    "IND": "Indianapolis Colts",
    "JAC": "Jacksonville Jaguars",
    "KCC": "Kansas City Chiefs",
    "LAR": "Los Angeles Rams",
    "MIA": "Miami Dolphins",
    "MIN": "Minnesota Vikings",
    "NEP": "New England Patriots",
    "NOS": "New Orleans Saints",
    "NYG": "New York Giants",
    "NYJ": "New York Jets",
    "OAK": "Oakland Raiders",
    "PHI": "Philadelphia Eagles",
    "PIT": "Pittsburgh Steelers",
    "SDC": "San Diego Chargers",
    "SEA": "Seattle Seahawks",
    "SFO": "San Francisco 49ers",
    "TBB": "Tampa Bay Buccaneers",
    "TEN": "Tennessee Titans",
    "WAS": "Washington Redskins",
}
